# Generated by Django 5.2 on 2025-04-18 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0003_migrate_existing_villages'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
