# Generated by Django 5.2 on 2025-04-18 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0005_userprofile_aadhaar_verified_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communityevent',
            options={'ordering': ['-start_date']},
        ),
        migrations.AddField(
            model_name='communityevent',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated budget for the event', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='communityevent',
            name='contact_person',
            field=models.CharField(blank=True, help_text='Person to contact for more information', max_length=100),
        ),
        migrations.AddField(
            model_name='communityevent',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=15),
        ),
        migrations.AddField(
            model_name='communityevent',
            name='expected_attendees',
            field=models.PositiveIntegerField(default=0, help_text='Expected number of attendees'),
        ),
        migrations.AddField(
            model_name='communityevent',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Whether the event is open to all village members'),
        ),
        migrations.AddField(
            model_name='communityevent',
            name='location',
            field=models.CharField(blank=True, help_text='Specific location within the village', max_length=200),
        ),
        migrations.AddField(
            model_name='communityevent',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes or instructions'),
        ),
        migrations.AddField(
            model_name='communityevent',
            name='registration_deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline for registration if required', null=True),
        ),
        migrations.AddField(
            model_name='communityevent',
            name='requires_registration',
            field=models.BooleanField(default=False, help_text='Whether attendees need to register'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='father_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='communityevent',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to='village.userprofile'),
        ),
        migrations.AlterField(
            model_name='communityevent',
            name='event_type',
            field=models.CharField(choices=[('festival', 'Festival'), ('meeting', 'Meeting'), ('puja', 'Puja'), ('sports', 'Sports Event'), ('education', 'Educational Event'), ('health', 'Health Camp'), ('cultural', 'Cultural Program'), ('social', 'Social Gathering'), ('development', 'Development Work'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='communityevent',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='village.village'),
        ),
    ]
