# Generated by Django 5.2 on 2025-04-18 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0006_alter_communityevent_options_communityevent_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='accepted', max_length=20),
        ),
        migrations.AddField(
            model_name='relationship',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='relationship_type',
            field=models.CharField(choices=[('family', 'Family'), ('friend', 'Friend'), ('neighbor', 'Neighbor'), ('colleague', 'Colleague'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together={('user', 'related_user')},
        ),
        migrations.CreateModel(
            name='RelationshipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('family', 'Family'), ('friend', 'Friend'), ('neighbor', 'Neighbor'), ('colleague', 'Colleague'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='village.userprofile')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='village.userprofile')),
            ],
            options={
                'unique_together': {('from_user', 'to_user')},
            },
        ),
    ]
