# Generated by Django 5.2 on 2025-04-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0007_relationship_status_relationship_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='banner_dismissed',
            field=models.BooleanField(default=False, help_text='Whether the user has dismissed the Aadhaar verification banner'),
        ),
    ]
