# Generated by Django 5.2 on 2025-04-19 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0008_userprofile_banner_dismissed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aadhaarverification',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aadhaar_verifications', to='village.userprofile'),
        ),
        migrations.RenameField(
            model_name='aadhaarverification',
            old_name='verification_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='aadhaarverification',
            old_name='verification_date',
            new_name='reviewed_at',
        ),
        migrations.RenameField(
            model_name='aadhaarverification',
            old_name='verified_by',
            new_name='reviewed_by',
        ),
        migrations.RenameField(
            model_name='aadhaarverification',
            old_name='created_at',
            new_name='submitted_at',
        ),
    ]
