# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0009_auto_20250419_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='aadhaarverification',
            name='front_image',
            field=models.ImageField(default='', upload_to='aadhaar/front/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aadhaarverification',
            name='back_image',
            field=models.ImageField(default='', upload_to='aadhaar/back/'),
            preserve_default=False,
        ),
    ] 