# Generated by Django 5.2 on 2025-04-19 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0010_add_aadhaar_images'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aadhaarverification',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.RemoveField(
            model_name='aadhaarverification',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='aadhaarverification',
            name='village',
        ),
        migrations.AddField(
            model_name='aadhaarverification',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aadhaarverification',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aadhaarverification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
